#!/usr/bin/env bash
set -Eeuo pipefail

APP_DIR="${2:-/opt/price-alert}"
STATE_DIR="/etc/price-alert"
STATE_FILE="$STATE_DIR/cloudflare-origin-lockdown.env"
SERVICE_NAME="price-alert-cloudflare-origin-lockdown"
IPSET_V4="price_alert_cloudflare4"
IPSET_V6="price_alert_cloudflare6"
RULE_COMMENT="price-alert-cloudflare-origin-lockdown"

die() { echo "Error: $*" >&2; exit 1; }
info() { echo "==> $*"; }

require_root() {
  [[ "${EUID}" -eq 0 ]] || die "Run this command as root."
}

ensure_dependencies() {
  command -v curl >/dev/null 2>&1 || die "curl is required."
  command -v ipset >/dev/null 2>&1 || die "ipset is required. Run the deployment install command again."
  command -v iptables >/dev/null 2>&1 || die "iptables is required."
  command -v ip6tables >/dev/null 2>&1 || die "ip6tables is required."
}

external_interface() {
  ip route get 1.1.1.1 | awk '{ for (field = 1; field <= NF; field++) if ($field == "dev") { print $(field + 1); exit } }'
}

refresh_ipset() {
  local live="$1"
  local family="$2"
  local source_url="$3"
  local next="${live}_next"

  ipset destroy "$next" 2>/dev/null || true
  ipset create "$next" hash:net family "$family"

  local count=0 cidr
  while read -r cidr; do
    [[ -n "$cidr" ]] || continue
    ipset add "$next" "$cidr"
    ((count += 1))
  done < <(curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 "$source_url")

  ((count > 0)) || die "Cloudflare returned no ${family} IP ranges."
  ipset create "$live" hash:net family "$family" -exist
  ipset swap "$live" "$next"
  ipset destroy "$next"
}

domain_uses_cloudflare_proxy() {
  local domain="$1"
  local ip
  while read -r ip; do
    [[ -n "$ip" ]] || continue
    if ipset test "$IPSET_V4" "$ip" >/dev/null 2>&1 || ipset test "$IPSET_V6" "$ip" >/dev/null 2>&1; then
      return 0
    fi
  done < <({ getent ahostsv4 "$domain" || true; getent ahostsv6 "$domain" || true; } | awk '{ print $1 }' | sort -u)
  return 1
}

write_trusted_proxy_config() {
  local config_file="$APP_DIR/caddy/cloudflare-trusted-proxies.caddy"
  local ipv4 ipv6
  ipv4="$(ipset save "$IPSET_V4" | awk '/^add / { print $3 }' | paste -sd ' ' -)"
  ipv6="$(ipset save "$IPSET_V6" | awk '/^add / { print $3 }' | paste -sd ' ' -)"
  [[ -n "$ipv4" && -n "$ipv6" ]] || die "Cloudflare IP sets are empty."

  cat > "$config_file" <<EOF
# Generated by scripts/cloudflare-origin-lockdown.sh. Do not edit manually.
servers {
  trusted_proxies static $ipv4 $ipv6
  trusted_proxies_strict
  client_ip_headers CF-Connecting-IP
}
EOF
}

write_default_trusted_proxy_config() {
  cat > "$APP_DIR/caddy/cloudflare-trusted-proxies.caddy" <<'EOF'
# Cloudflare origin lockdown is disabled by default.
# scripts/deploy.sh generates trusted proxy directives here when enabled.
EOF
}

ensure_docker_user_chain() {
  local tool="$1"
  if ! "$tool" -S DOCKER-USER >/dev/null 2>&1; then
    "$tool" -N DOCKER-USER
    "$tool" -I FORWARD 1 -j DOCKER-USER
  fi
}

add_drop_rule() {
  local tool="$1"
  local chain="$2"
  local interface="$3"
  local set_name="$4"

  "$tool" -C "$chain" -i "$interface" -p tcp -m multiport --dports 80,443 \
    -m set ! --match-set "$set_name" src -m comment --comment "$RULE_COMMENT" -j DROP 2>/dev/null ||
  "$tool" -I "$chain" 1 -i "$interface" -p tcp -m multiport --dports 80,443 \
    -m set ! --match-set "$set_name" src -m comment --comment "$RULE_COMMENT" -j DROP
}

delete_drop_rule() {
  local tool="$1"
  local chain="$2"
  local interface="$3"
  local set_name="$4"

  while "$tool" -D "$chain" -i "$interface" -p tcp -m multiport --dports 80,443 \
    -m set ! --match-set "$set_name" src -m comment --comment "$RULE_COMMENT" -j DROP 2>/dev/null; do
    :
  done
}

install_systemd_timer() {
  cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=Refresh Price Alert Cloudflare origin firewall rules
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/bin/env bash $APP_DIR/scripts/cloudflare-origin-lockdown.sh apply $APP_DIR
ExecStartPost=-/usr/bin/docker compose --project-directory $APP_DIR -f $APP_DIR/docker-compose.yml restart caddy
EOF

  cat > "/etc/systemd/system/${SERVICE_NAME}.timer" <<EOF
[Unit]
Description=Refresh Price Alert Cloudflare origin firewall rules daily

[Timer]
OnBootSec=2min
OnUnitActiveSec=1d
Persistent=true

[Install]
WantedBy=timers.target
EOF

  systemctl daemon-reload
  systemctl enable --now "${SERVICE_NAME}.timer"
}

apply_lockdown() {
  local domain="$1"
  ensure_dependencies
  [[ -d "$APP_DIR/caddy" ]] || die "Expected application directory at $APP_DIR."

  local interface
  interface="$(external_interface)"
  [[ -n "$interface" ]] || die "Could not determine the external network interface."

  info "Refreshing Cloudflare IP ranges"
  refresh_ipset "$IPSET_V4" inet "https://www.cloudflare.com/ips-v4"
  refresh_ipset "$IPSET_V6" inet6 "https://www.cloudflare.com/ips-v6"
  domain_uses_cloudflare_proxy "$domain" || die "$domain does not resolve to a Cloudflare proxy IP. Enable the Cloudflare proxy before enabling origin lockdown."

  ensure_docker_user_chain iptables
  ensure_docker_user_chain ip6tables
  add_drop_rule iptables INPUT "$interface" "$IPSET_V4"
  add_drop_rule iptables DOCKER-USER "$interface" "$IPSET_V4"
  add_drop_rule ip6tables INPUT "$interface" "$IPSET_V6"
  add_drop_rule ip6tables DOCKER-USER "$interface" "$IPSET_V6"

  install -d -m 700 "$STATE_DIR"
  cat > "$STATE_FILE" <<EOF
INTERFACE=$interface
EOF
  chmod 600 "$STATE_FILE"
  write_trusted_proxy_config
  install_systemd_timer
}

remove_lockdown() {
  local interface=""
  if [[ -f "$STATE_FILE" ]]; then
    # shellcheck disable=SC1090
    . "$STATE_FILE"
    interface="${INTERFACE:-}"
  fi
  interface="${interface:-$(external_interface)}"

  if [[ -n "$interface" ]]; then
    delete_drop_rule iptables INPUT "$interface" "$IPSET_V4"
    delete_drop_rule iptables DOCKER-USER "$interface" "$IPSET_V4"
    delete_drop_rule ip6tables INPUT "$interface" "$IPSET_V6"
    delete_drop_rule ip6tables DOCKER-USER "$interface" "$IPSET_V6"
  fi
  ipset destroy "$IPSET_V4" 2>/dev/null || true
  ipset destroy "$IPSET_V6" 2>/dev/null || true
  systemctl disable --now "${SERVICE_NAME}.timer" 2>/dev/null || true
  rm -f "/etc/systemd/system/${SERVICE_NAME}.service" "/etc/systemd/system/${SERVICE_NAME}.timer" "$STATE_FILE"
  rmdir "$STATE_DIR" 2>/dev/null || true
  systemctl daemon-reload
  [[ -d "$APP_DIR/caddy" ]] && write_default_trusted_proxy_config
}

main() {
  require_root
  local command="${1:-}"
  case "$command" in
    apply)
      [[ $# -eq 2 ]] || die "Usage: $0 apply <app-directory>"
      # shellcheck disable=SC1090
      . "$APP_DIR/.env"
      [[ -n "${DOMAIN:-}" ]] || die "DOMAIN is missing from $APP_DIR/.env."
      apply_lockdown "$DOMAIN"
      ;;
    remove)
      [[ $# -eq 2 ]] || die "Usage: $0 remove <app-directory>"
      remove_lockdown
      ;;
    *) die "Usage: $0 {apply|remove} <app-directory>" ;;
  esac
}

main "$@"
